
services:
  grafana:
    container_name: grafana_compose
    image: grafana/grafana:latest
    # ports:
    #   - "3000:3000"
    volumes:
      - ./grafana:/etc/grafana/provisioning
    networks:
      - monitoring

  loki:
    image: grafana/loki:latest
    user: root
    container_name: loki
    # ports:
    #   - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
      - ./data/loki:/data/loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - monitoring

  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: otel
    volumes:
      - ./otel-config.yaml:/etc/otel/config.yaml
    command:
      - '--config=/etc/otel/config.yaml'
    # ports:
    #   - "4317:4317" #grpc
    #   - "4318:4318" #http
    depends_on:
      - loki
    networks:
      - monitoring

  nginx:
    image: nginx:latest
    container_name: nginx_compose
    ports:
      - "12345:12345"
      - "80:80"
      - "4317:4317"
      - "3100:3100"
    volumes:
      - ./loki.conf:/etc/nginx/conf.d/loki.conf
      - ./otel.conf:/etc/nginx/conf.d/otel.conf
      - ./grafana.conf:/etc/nginx/conf.d/grafana.conf
      - ./htpasswd_loki:/etc/nginx/.htpasswd_loki
      - ./htpasswd_otel:/etc/nginx/.htpasswd_otel
      - /dev/null:/etc/nginx/conf.d/default.conf  # Disable the default configuration
    # command: /bin/sh -c "[ ! -d /etc/nginx/sites-enabled ] && mkdir /etc/nginx/sites-enabled; ln -s /etc/nginx/sites-available/loki.conf /etc/nginx/sites-enabled/loki.conf && ln -s /etc/nginx/sites-available/otel.conf /etc/nginx/sites-enabled/otel.conf && ln -s /etc/nginx/sites-available/grafana.conf /etc/nginx/sites-enabled/grafana.conf && nginx -g 'daemon off;'"
    # command: /bin/sh -c "mkdir -p /etc/nginx/sites-enabled && ln -s /etc/nginx/sites-available/*.conf /etc/nginx/sites-enabled/ && nginx -g 'daemon off;'"
    networks:
      - monitoring
    depends_on:
      - grafana
      - loki
      - otel-collector

networks:
  monitoring:
