apiVersion: 1

datasources:
  - name: CloudWatch
    uid: de3t7rxv00we8c
    type: cloudwatch
    access: proxy
    editable: true
    isDefault: false
    jsonData:
      authType: default
      defaultRegion: ap-south-1
